# Generated by Django 4.2.11 on 2024-04-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_has_confirmed_alter_user_create_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfirmCode',
            new_name='Confirm',
        ),
    ]
